### ISSUE TITLE
Accessing / over HTTPS redirects to eda/ over HTTP

### ISSUE THREAD

**Issue by kurokobo** [ansible/eda-server-operator#155]
#### Description

On `0.0.11` with the latest eda-ui, accessing `https://eda.example.com` redirects to `http://eda.example.com/eda/`.

#### Steps to reproduce

- Deploy EDA with Ingress with TLS cert
  ```yaml
  ingress_type: ingress
  ingress_tls_secret: eda-secret-tls
  hostname: eda.example.com
  ```
- Access `https://eda.example.com`

#### Additional information

With above configuration, TLS is terminated on Ingress resource, so on the nginx side, `$scheme` is determined as plain HTTP instead of HTTPS.
