### ISSUE TITLE
The used redis latest image has been removed  

### ISSUE THREAD

**Issue by ThorstenHeck** [ansible/eda-server-operator#188]
Hello!

The used Redis Image had some breaking changes, regarding the default image tag.

https://quay.io/repository/sclorg/redis-6-c9s?tab=info

It may be helpful to change the default value from **default** to **c9s** to keep it running. 
https://github.com/ansible/eda-server-operator/blob/1.0.0/roles/redis/defaults/main.yml#L10

Here an explicit example how to change it via configuration:

```yaml
---
spec:
  ...
  redis_image: quay.io/sclorg/redis-6-c9s
  redis_image_version: c9s
```
