### ISSUE TITLE
Change the location of the eda-ui

### ISSUE THREAD

**Issue by washburnjoe** [ansible/eda-server-operator#263]
Since we use twistlock we cant pull the eda-ui from quay.  Is it possible to make a change to image location or I guess worst case just disable the UI so it does not try and deploy with the operator?

**Comment by dsavineau** [comment]
> Is it possible to make a change to image location

I don't think this would be possible

However, you can sync that image to a different registry and override the default web image URL

```yaml
spec:
  image_web: myregistry/mynamespace/myimage
  image_web_version: mytag
```

> I guess worst case just disable the UI so it does not try and deploy with the operator?

```yaml
spec:
  ui_disabled: true
```
