### ISSUE TITLE
Getting default nginx screen when trying to access eda server

### ISSUE THREAD

**Issue by philip860** [ansible/eda-server-operator#279]
When running eda-operator with tag: 1.0.2 after ALL pods initialize, instead of being redirected to the login screen for the EDA-UI. I am getting the generic "Welcome to nginx!" screen.

I have also observed the when using the eda-operator with tag: main, it does load the login page correctly, however that version of the operator uses postgres15, and a bunch of the pods fail and error out. So when it comes time to login to the eda-ui, I receive a "bad gateway" error message.

Currently my system is running ubuntu 22 with k3s.

Phil

**Comment by jeffkala** [comment]
+1 having this issue.

**Comment by sarahwinters-UTD** [comment]
1.0.1 does not appear to be functional on a new setup either. The quay image for the eda-ui container appears to be missing. I had to go to 1.0.0 to get it working.

**Comment by Tfinn92** [comment]
I've been fighting to get this up and running on our OCP cluster and I finally got it to a point that I can access the GUI. Just for anyone else's sake, here's the method I took.

1. Git clone the main branch of this repo
2. cd into the cloned repo folder
3. Create my kustomization.yaml to look like this

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config/default

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/eda-server-operator
    newTag: main

# Specify a custom namespace in which to install EDA
namespace: eda
```
4. kubectl apply -k .
5. Once the operator pods were ready, create the eda-demo.yaml file to have this inside it:
```yaml
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: my-eda
spec:
  automation_server_url: https://awx.company.com  #<-- obviously replace with your AWX instance
  no_log: false
  redis_image: quay.io/sclorg/redis-6-c9s
  redis_image_version: c9s
```
6. kubectl apply -f eda-demo.yaml
7. Wait for everything to come online
8. Since I am running OpenShift, I also had to expose the service to create the route 
```bash
oc expose service my-eda-ui
```
9. I had to tweak it to use TLS termination "Edge" 
10. Profit.

I hope this can at least help someone else get a little closer. I tried this on Kubernetes using LongHorn and I could NOT get the Postgres DB to come online no matter what I did. Openshift Cluster with VAST CSI driver for storage worked like a charm though.
