### ISSUE TITLE
Latest version trying to provision PostgreSQL 13

### ISSUE THREAD

**Issue by AGirin** [ansible/eda-server-operator#282]
Hello,

I deployed test eda according to the basic setup document. This is what I see: 

![Image](https://github.com/user-attachments/assets/d281e597-752a-4e86-a64f-0ee7ab5845d1)

I think it was suppose to deploy PostgreSQL 15? All defaults are set to use 15 but is still uses 13.. And here is the issue:

mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied

This is what I have in my files:

kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config/default

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/eda-server-operator
    newTag: 1.0.2

# Specify a custom namespace in which to install EDA
namespace: eda
```

eda-demo.yml:

```
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda-test
  namespace: eda
spec:
  no_log: false
  automation_server_url: http://awx-test-service.awx-test:80
  database:
    postgres_data_volume_init: true
```

My understanding that  postgres_data_volume_init: true should work for PostgreSQL 15 (it does in AWX operator).

How do I make it work with PostgreSQL 13? Or better yet - how do I force eda to use PostgreSQL 15 image?  

Thanks,

Andrew
