### ISSUE TITLE
Event stream is not working as expected

### ISSUE THREAD

**Issue by AGirin** [ansible/eda-server-operator#285]
I have enable Ingress and UI/API works just fine. But event streams do not. URL displayed in UI is not correct. You can get more info here: https://github.com/ansible/eda-server/issues/1278

I see there are two rules in ALB created by operator - one for UI and one for event streams. When I use URL displayed in UI like:

https://test.test.local/eda-event-streams/api/eda/v1/external_event_stream/<UID>/post/ I get 405 error from nginx. 

If I remove eda-event-strems from URL like this:

https://test.test.local/api/eda/v1/external_event_stream/<UID>/post/

things work as expected. According to EDA server guys this is not entirely correct as at this point we use API workers to receive events not event stream ones. 

This is my config for EDA operator:

```
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda-test
  namespace: eda
spec:
  ingress_type: ingress
  ingress_path: /
  ingress_path_type: Prefix
  ingress_annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/certificate-arn: >-
      <certificate arn>
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=1800,routing.http.drop_invalid_header_fields.enabled=true,routing.http2.enabled=true
    alb.ingress.kubernetes.io/tags: application=eda-test
  hostname: test.test.local
  no_log: false
  automation_server_url: https://awx.test.local:443
  database:
    postgres_data_volume_init: true
  public_base_url: https://test.test.local/
  extra_settings:
    - setting: ALLOW_LOCAL_ASSIGNING_JWT_ROLES
      value: "true"
    - setting: EDA_MAX_RUNNING_ACTIVATIONS
      value: "16"
```

I see there are two template files to create Ingress for event streams:

https://github.com/ansible/eda-server-operator/blob/main/roles/eda/templates/eda-event-stream.ingress.yaml.j2

and 

https://github.com/ansible/eda-server-operator/blob/main/roles/eda/templates/eda-ui.ingress.yaml.j2

I believe last one was used to configure my Ingress, as it includes both UI and Event Streams. 

<img width="1031" alt="Image" src="https://github.com/user-attachments/assets/907bb70c-0f80-4804-a211-881e01d0c101" />

Both rules use the same host header test.test.local. 

Am I missing something in my setup?

**Comment by Alex-Izquierdo** [comment]
I think we have an issue when handling the `public_base_url` variable because it is also used to configure a redirect in the UI. It means, defining it is equivalent to say that the deployment works in "platform mode" and not in the standalone mode. 

Instead of defining `public_base_url`, override the value of `EDA_EVENT_STREAM_BASE_URL` as it is described here:
https://github.com/ansible/eda-server-operator?tab=readme-ov-file#enable-event-streams

**Comment by AGirin** [comment]
@Alex-Izquierdo I actually did try that.. No luck.. Same error. 

```
  extra_settings:
    - setting: ALLOW_LOCAL_ASSIGNING_JWT_ROLES
      value: "true"
    - setting: EDA_MAX_RUNNING_ACTIVATIONS
      value: "16"
    - setting: EDA_EVENT_STREAM_BASE_URL
      value: "https://test.test.local/eda-event-streams"
```

What I don't understand - is that event stream name should be the same as my UI name? Like UI is https://test.test.local and Event Streams also set to https://test.test.local? I actually tried setting this to mytest.test.local but nothing changed in ALB, what changed is URL displayed in the UI... 

Do I need to create separate Ingress for event streams specifically? If yes - then I don' understand why operator create rules for event streams in ALB dedicated to UI...
